console.log((((2) + (3)) | 0));
console.log((((10) - (4)) | 0));
console.log((Math.imul((6), (7))));
console.log((((100) / ((((d) => (d === 0 || d === 0n) ? (() => { throw new Error('Attempted to divide by zero.') })() : d)((7))))) | 0));
console.log((((100) % ((((d) => (d === 0 || d === 0n) ? (() => { throw new Error('Attempted to divide by zero.') })() : d)((7))))) | 0));
console.log((((3) - (10)) | 0));
console.log(((((((7) - (3)) | 0)) - (2)) | 0));
console.log(((((((100) / ((((d) => (d === 0 || d === 0n) ? (() => { throw new Error('Attempted to divide by zero.') })() : d)((5))))) | 0)) / ((((d) => (d === 0 || d === 0n) ? (() => { throw new Error('Attempted to divide by zero.') })() : d)((2))))) | 0));
console.log((((2) + ((Math.imul((3), (4))))) | 0));
console.log(((((Math.imul(((((10) + (5)) | 0)), (2)))) - (3)) | 0));
console.log(((((((100) - ((Math.imul((2), (3))))) | 0)) + (1)) | 0));
console.log((((-7) / ((((d) => (d === 0 || d === 0n) ? (() => { throw new Error('Attempted to divide by zero.') })() : d)((2))))) | 0));
console.log((((-7) % ((((d) => (d === 0 || d === 0n) ? (() => { throw new Error('Attempted to divide by zero.') })() : d)((2))))) | 0));
console.log((((2000000000) + (2000000000)) | 0));
console.log((Math.imul((100000), (100000))));
