<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RefPack.fs" />
    <Compile Include="ClrTuples.fs" />
    <Compile Include="AttributeRows.fs" />
    <Compile Include="MetadataSymbols.fs" />
    <Compile Include="ClrSymbolProviders.fs" />
    <Compile Include="ProjectInfo.fs" />
    <Compile Include="TyparMarkers.fs" />
    <Compile Include="UnionRegime.fs" />
    <Compile Include="PlatformTypeIds.fs" />
    <Compile Include="Unmanagedness.fs" />
    <Compile Include="UnionCaseShape.fs" />
    <Compile Include="UnionPlacements.fs" />
    <Compile Include="Types.fs" />
    <Compile Include="Cil.fs" />
    <Compile Include="Metadata.fs" />
    <Compile Include="ICodegenProvider.fs" />
    <Compile Include="CodegenSymbols.fs" />
    <Compile Include="ClrEnv.fs" />
    <Compile Include="ClrEncoder.fs" />
    <Compile Include="ClrGenerics.fs" />
    <Compile Include="ClrExternalMembers.fs" />
    <Compile Include="ClrRecipes.fs" />
    <Compile Include="ClrProvider.fs" />
    <Compile Include="IlIr.fs" />
    <Compile Include="EmitTypes.fs" />
    <Compile Include="EmitLower.fs" />
    <Compile Include="EmitClosures.fs" />
    <Compile Include="EmitResolve.fs" />
    <Compile Include="ClrHoleFormat.fs" />
    <Compile Include="EmitFormat.fs" />
    <Compile Include="EmitDispatch.fs" />
    <Compile Include="EmitPattern.fs" />
    <Compile Include="EmitBindings.fs" />
    <Compile Include="EmitLoops.fs" />
    <Compile Include="EmitMatch.fs" />
    <Compile Include="EmitConstruct.fs" />
    <Compile Include="EmitMember.fs" />
    <Compile Include="EmitCall.fs" />
    <Compile Include="EmitIntrinsic.fs" />
    <Compile Include="EmitExpr.fs" />
    <Compile Include="EmitStructural.fs" />
    <Compile Include="EmitStructuralFormat.fs" />
    <Compile Include="Emit.fs" />
    <Compile Include="ModuleClassPlan.fs" />
    <Compile Include="CodegenTypes.fs" />
    <Compile Include="LayoutModel.fs" />
    <Compile Include="LayoutNodes.fs" />
    <Compile Include="UnionLayoutNodes.fs" />
    <Compile Include="Layout.fs" />
    <Compile Include="Materialise.fs" />
    <Compile Include="AssemblerScaffold.fs" />
    <Compile Include="ClosureVerdictRewrite.fs" />
    <Compile Include="AttributeRowPrep.fs" />
    <Compile Include="NominalRegistration.fs" />
    <Compile Include="Assembler.fs" />
    <Compile Include="NominalShared.fs" />
    <Compile Include="UnionEmit.fs" />
    <Compile Include="NominalEmit.fs" />
    <Compile Include="Codegen.fs" />
    <Compile Include="ClrDriver.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\XParsec.FSharp.SemanticAnalysis\XParsec.FSharp.SemanticAnalysis.fsproj" />
    <ProjectReference Include="..\XParsec.FSharp.Codegen.Common\XParsec.FSharp.Codegen.Common.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" />
  </ItemGroup>
</Project>