<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="NumberCovariance.fs" />
    <Compile Include="JsNativeSymbols.fs" />
    <Compile Include="TsManifestTypes.fs" />
    <Compile Include="TsManifestMembers.fs" />
    <Compile Include="TsManifestProvider.fs" />
    <Compile Include="JsAst.fs" />
    <Compile Include="JsPrint.fs" />
    <Compile Include="JsRuntime.fs" />
    <Compile Include="JsEmitHelpers.fs" />
    <Compile Include="JsFlatFns.fs" />
    <Compile Include="JsExternalMembers.fs" />
    <Compile Include="EmitJsCapabilities.fs" />
    <Compile Include="EmitJsTypes.fs" />
    <Compile Include="EmitJsContext.fs" />
    <Compile Include="EmitJsFormat.fs" />
    <Compile Include="EmitJsMembers.fs" />
    <Compile Include="EmitJs.fs" />
    <Compile Include="Codegen.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\XParsec.FSharp.SemanticAnalysis\XParsec.FSharp.SemanticAnalysis.fsproj" />
    <ProjectReference Include="..\XParsec.FSharp.Codegen.Common\XParsec.FSharp.Codegen.Common.fsproj" />
    <ProjectReference Include="..\Vesper.Ts.Manifest.Schema\Vesper.Ts.Manifest.Schema.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>