namespace Vesper

/// <summary>An abbreviation for the CLI type <see cref="T:System.IntPtr"/>.</summary>
///
/// <category>Basic Types</category>
type nativeint =
    extern with

    static member (&&&): x: nativeint * y: nativeint -> nativeint

    static member (|||): x: nativeint * y: nativeint -> nativeint

    static member (^^^): x: nativeint * y: nativeint -> nativeint

    static member (~~~): value: nativeint -> nativeint

    static member (<<<): value: nativeint * shift: int -> nativeint

    static member (>>>): value: nativeint * shift: int -> nativeint

/// <summary>An abbreviation for the CLI type <see cref="T:System.UIntPtr"/>.</summary>
///
/// <category>Basic Types</category>
type unativeint =
    extern with

    static member (&&&): x: unativeint * y: unativeint -> unativeint

    static member (|||): x: unativeint * y: unativeint -> unativeint

    static member (^^^): x: unativeint * y: unativeint -> unativeint

    static member (~~~): value: unativeint -> unativeint

    static member (<<<): value: unativeint * shift: int -> unativeint

    static member (>>>): value: unativeint * shift: int -> unativeint

/// <summary>Represents an unmanaged pointer in F# code.</summary>
///
/// <remarks>This type should only be used when writing F# code that interoperates
/// with native code. Use of this type in F# code may result in
/// unverifiable code being generated. Conversions to and from the
/// <see cref="T:Microsoft.FSharp.Core.nativeint" /> type may be required. Values of this type can be generated
/// by the functions in the <c>NativeInterop.NativePtr</c> module.</remarks>
///
/// <category>ByRef and Pointer Types</category>
type nativeptr<'T when 'T : unmanaged> = extern

/// <summary>Represents an untyped unmanaged pointer in F# code.</summary>
///
/// <remarks>This type should only be used when writing F# code that interoperates
/// with native code. Use of this type in F# code may result in
/// unverifiable code being generated. Conversions to and from the
/// <see cref="T:Microsoft.FSharp.Core.nativeint" /> type may be required. Values of this type can be generated
/// by the functions in the <c>NativeInterop.NativePtr</c> module.</remarks>
///
/// <category>ByRef and Pointer Types</category>
type voidptr = extern

/// <summary>Represents an Common IL (Intermediate Language) Signature Pointer.</summary>
///
/// <remarks>This type should only be used when writing F# code that interoperates
/// with other .NET languages that use generic Common IL Signature Pointers.
/// Use of this type in F# code may result in unverifiable code being generated.
/// Because of the rules of Common IL Signature Pointers, you cannot use this type in generic type parameters,
/// resulting in compiler errors. As a result, you should convert this type to <see cref="T:Microsoft.FSharp.Core.nativeptr{T}" />
/// for use in F#. Note that Common IL Signature Pointers exposed by other .NET languages are converted to
/// <see cref="T:Microsoft.FSharp.Core.nativeptr{T}" /> or <see cref="T:Microsoft.FSharp.Core.voidptr" /> automatically by F#,
/// and F# also shows generic-specialized typed native pointers correctly to other .NET languages as Common IL Signature Pointers.
/// However, generic typed native pointers are shown as <see cref="T:System.IntPtr"/> to other .NET languages.
/// For other languages to interpret generic F# typed native pointers correctly, you should expose this type or
/// <see cref="T:Microsoft.FSharp.Core.voidptr" /> instead of <see cref="T:Microsoft.FSharp.Core.nativeptr{T}" />.
/// Values of this type can be generated by the functions in the <c>NativeInterop.NativePtr</c> module.</remarks>
///
/// <category>ByRef and Pointer Types</category>
type ilsigptr<'T> = extern
